[features]
seeds = false
skip-lint = false

[programs.localnet]
solrip_contract = "RiPnkGhwuYN7ET3aMuGUAdomE3CFxBPUSonXsJrW4HS"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
client = "yarn run ts-node client/*.ts"
